version: "3.2"

services:

  mysql:
    image: mysql:5.6
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=evething2
      - MYSQL_PASSWORD=hunter2
      - MYSQL_DATABASE=evething2
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis-data:/data

  app:
    build: .
    environment:
      - DB_HOST=mysql
      - DB_NAME=evething2
      - DB_USER=evething2
      - DB_PASSWORD=hunter2
      - ESI_CLIENT_ID=98b1c11875b0475cb97c84336766ae48
      - ESI_SECRET_KEY=F9l0IcaKBBjiqUovieKSezwSlEBZftJc9aYDbUBg
      - ESI_CALLBACK_URL=http://127.0.0.1/account/sso/callback/
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app
      - static:/static
    depends_on:
      - mysql
      - redis

  app-celery:
    entrypoint: ./celery.sh
    build: .
    environment:
      - DB_HOST=mysql
      - DB_NAME=evething2
      - DB_USER=evething2
      - DB_PASSWORD=hunter2
      - ESI_CLIENT_ID=98b1c11875b0475cb97c84336766ae48
      - ESI_SECRET_KEY=F9l0IcaKBBjiqUovieKSezwSlEBZftJc9aYDbUBg
      - ESI_CALLBACK_URL=http://127.0.0.1/account/sso/callback/
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app
      - static:/static
    depends_on:
      - mysql
      - redis

  nginx:
    build: nginx/
    volumes:
      - static:/static
    ports:
      - "8000:8000"
    depends_on:
      - app


volumes:
  mysql-data:
  redis-data:
  static: